name: Diff views

on: push

jobs:
  diff:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [v3.3.1, v3.4.1, v3.5.1]
    steps:
    - name: Checkout current plugin
      uses: actions/checkout@v4
      with:
        path: plugin
        sparse-checkout: |
          frontend/views

    - name: Checkout ArchivesSpace baseline repo
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        fetch-tags: true
        ref: v3.3.1
        repository: lorawoodford/archivesspace
        path: archivesspace-baseline
        sparse-checkout: |
          frontend/app/views

    - name: Checkout ArchivesSpace repo
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        fetch-tags: true
        ref: ${{ matrix.version }}
        repository: lorawoodford/archivesspace
        path: archivesspace
        sparse-checkout: |
          frontend/app/views

    - name: Diff with baseline
      id: baseline
      run: echo "::set-output name=baseline_changes::$(git diff --diff-filter=M --shortstat ${{ github.workspace }}/archivesspace-baseline/frontend/app/views ${{ github.workspace }}/plugin/frontend/views)"
   
    - name: Diff with new versions
      id: new
      run: |
        echo "::set-output name=new_changes::$(git diff --diff-filter=M --shortstat ${{ github.workspace }}/archivesspace/frontend/app/views ${{ github.workspace }}/plugin/frontend/views)"
        echo "::set-output name=review_changes::$(git diff --diff-filter=M ${{ github.workspace }}/archivesspace/frontend/app/views ${{ github.workspace }}/plugin/frontend/views  | egrep "^\-" | egrep "^\+")"

    - name: Matching diffs
      if: ${{ steps.baseline.outputs.baseline_changes == steps.new.outputs.new_changes }}
      run: |
        echo "${{ steps.baseline.outputs.baseline_changes }}"
        echo "${{ steps.new.outputs.new_changes }}"
        echo "We match"

    - name: New diffs
      if: ${{ steps.baseline.outputs.baseline_changes != steps.new.outputs.new_changes }}
      run: |
        echo "We do not match"
        echo "${{ steps.new.outputs.review_changes }}"
        exit 1
