name: Diff views

on: push

jobs:
  diff:
    runs-on: ubuntu-latest
    env:
      PROD_ARCHIVESSPACE_VERSION: v3.3.1
    strategy:
      matrix:
        version: [v3.3.1, v3.4.1, v3.5.1]
    steps:
    - name: Checkout current plugin
      uses: actions/checkout@v4
      with:
        path: plugin
        sparse-checkout: |
          frontend/views
          .archivesspace-version

    - name: Checkout ArchivesSpace baseline repo
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        fetch-tags: true
        ref: v3.3.1
        repository: lorawoodford/archivesspace
        path: archivesspace-baseline
        sparse-checkout: |
          frontend/app/views

    - name: Checkout ArchivesSpace repo
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        fetch-tags: true
        ref: ${{ matrix.version }}
        repository: lorawoodford/archivesspace
        path: archivesspace
        sparse-checkout: |
          frontend/app/views

    - name: Diff with baseline
      id: baseline
      run: |
        echo "::set-output name=baseline_changes::$(git diff --diff-filter=M --shortstat ${{ github.workspace }}/archivesspace-baseline/frontend/app/views ${{ github.workspace }}/plugin/frontend/views)"
   
    - name: Diff with new versions
      id: new
      run: |
        echo "::set-output name=new_changes::$(git diff --diff-filter=M --shortstat ${{ github.workspace }}/archivesspace/frontend/app/views ${{ github.workspace }}/plugin/frontend/views)"

    - name: Diffs match
      continue-on-error: true
      if: ${{ steps.baseline.outputs.baseline_changes == steps.new.outputs.new_changes }}
      run: |
        echo "${{ steps.baseline.outputs.baseline_changes }}"
        echo "${{ steps.new.outputs.new_changes }}"
        echo "All views overridden by this plugin match v3.3.1 of ArchivesSpace"

    - name: Diffs do not match
      if: ${{ steps.baseline.outputs.baseline_changes != steps.new.outputs.new_changes }}
      run: |
        echo "$PROD_ARCHIVESSPACE_VERSION"
        echo "Some views overridden by this plugin do not match those in ArchivesSpace ${{ matrix.version }}.  See:"
        echo "::set-output name=review_changes::$(git diff --diff-filter=M -w --color -- ${{ github.workspace }}/archivesspace/frontend/app/views ${{ github.workspace }}/plugin/frontend/views)"
        exit 1
